/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2.etapa1_guilhermefernandes_tiagoreis_antonioemilio;

/**
 *
 * @author guilh
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_Desktop = new javax.swing.JDesktopPane();
        btn_CadastrarCliente = new javax.swing.JButton();
        btn_cadastrarProduto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_BuscarUsuario = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel_Desktop.setBackground(new java.awt.Color(255, 204, 204));

        btn_CadastrarCliente.setText("Cadastrar Cliente");
        btn_CadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarClienteActionPerformed(evt);
            }
        });

        btn_cadastrarProduto.setText("Cadastrar Produto");
        btn_cadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarProdutoActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente");

        jLabel2.setText("Produto");

        btn_BuscarUsuario.setText("Buscar / Excluir  Cliente");
        btn_BuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarUsuarioActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar / Excluir Produto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Comprar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Alterar Produto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Alterar Cliente");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setText("Relatorio de Compras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        painel_Desktop.setLayer(btn_CadastrarCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel_Desktop.setLayer(btn_cadastrarProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel_Desktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel_Desktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel_Desktop.setLayer(btn_BuscarUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel_Desktop.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel_Desktop.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel_Desktop.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel_Desktop.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel_Desktop.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painel_DesktopLayout = new javax.swing.GroupLayout(painel_Desktop);
        painel_Desktop.setLayout(painel_DesktopLayout);
        painel_DesktopLayout.setHorizontalGroup(
            painel_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_DesktopLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(painel_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painel_DesktopLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_BuscarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_CadastrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(painel_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(btn_cadastrarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(122, 122, 122))
        );
        painel_DesktopLayout.setVerticalGroup(
            painel_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_DesktopLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(painel_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrarProduto)
                    .addComponent(btn_CadastrarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_BuscarUsuario)
                    .addComponent(jButton3))
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarProdutoActionPerformed
        CadastrarProduto prod = new CadastrarProduto();
        painel_Desktop.add(prod);
        prod.setVisible(true);
    }//GEN-LAST:event_btn_cadastrarProdutoActionPerformed

    private void btn_CadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarClienteActionPerformed
        
        CadastrarUsuario  cad = new CadastrarUsuario();
        painel_Desktop.add(cad);
        cad.setVisible(true);
    }//GEN-LAST:event_btn_CadastrarClienteActionPerformed

    private void btn_BuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarUsuarioActionPerformed
        BuscarUsuario busca = new BuscarUsuario();
        painel_Desktop.add(busca);
        busca.setVisible(true);
    }//GEN-LAST:event_btn_BuscarUsuarioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       BuscarProduto busca = new BuscarProduto();
       painel_Desktop.add(busca);
       busca.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AlterarCliente alterar = new AlterarCliente();
        painel_Desktop.add(alterar);
        alterar.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        AlterarProduto alterar = new AlterarProduto();
        painel_Desktop.add(alterar);
        alterar.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        JanelaCompra janela = new JanelaCompra();
        painel_Desktop.add(janela);
        janela.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        RelatorioCompras rel = new RelatorioCompras();
        painel_Desktop.add(rel);
        rel.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    public static void main(String[] args) {
        Servico.getInstancia().lerCliente("DadosClientes.ser");
        Servico.getInstancia().lerProduto("DadosProdutos.ser");
        Servico.getInstancia().lerCompra("DadosCompras.ser");
        Menu menu = new Menu();
        menu.setVisible(true);
        
 
    }
    
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BuscarUsuario;
    private javax.swing.JButton btn_CadastrarCliente;
    private javax.swing.JButton btn_cadastrarProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JDesktopPane painel_Desktop;
    // End of variables declaration//GEN-END:variables
}
